/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppearanceTabs: typeof import('./../components/AppearanceTabs.vue')['default']
    AppLogo: typeof import('./../components/AppLogo.vue')['default']
    AppLogoIcon: typeof import('./../components/AppLogoIcon.vue')['default']
    DeleteUser: typeof import('./../components/DeleteUser.vue')['default']
    Heading: typeof import('./../components/Heading.vue')['default']
    HeadingSmall: typeof import('./../components/HeadingSmall.vue')['default']
    PlaceholderPattern: typeof import('./../components/PlaceholderPattern.vue')['default']
    TextLink: typeof import('./../components/TextLink.vue')['default']
  }
}
